# Generated by Django 3.0.5 on 2022-04-25 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 13, 55, 59293)),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images\\'),
        ),
        migrations.AlterField(
            model_name='takenexam',
            name='done_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 25, 11, 13, 55, 69292)),
        ),
    ]
